version: '3.8'

services:
  smart-contract-verifier:
    platform: linux/x86_64
    image: amazechain/smart-contract-verifier:main
    pull_policy: always
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ../envs/common-smart-contract-verifier.env
    ports:
      - 8150:8050
